# on:
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   eslint:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v3
#         with:
#          node-version: '12'
#       - name: Instala dependências
#         run: npm i
#       - name: verifica o pacote
#         run: npx eslint
